//
//  Fujian.h
//  ProjectName
//
//  Created by AuthorName on 2019/10/22.
//  Copyright © 2019 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef NS_ENUM(NSInteger, FujianResizingBehavior)
{
    FujianResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    FujianResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    FujianResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    FujianResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

};

extern CGRect FujianResizingBehaviorApply(FujianResizingBehavior behavior, CGRect rect, CGRect target);


@interface Fujian : NSObject

// Drawing Methods
+ (void)drawCanvas2;
+ (void)drawCanvas2WithFrame: (CGRect)targetFrame resizing: (FujianResizingBehavior)resizing;

@end
